### ISSUE TITLE
Recommendation for emoji.json

### ISSUE THREAD

**Issue by HaleTom** [b4b4r07/emoji-cli#15]
Which `emoji.json` works best with this plugin?

**Comment by HaleTom** [comment]
https://github.com/amio/emoji.json
https://github.com/github/gemoji/blob/master/db/emoji.json
https://github.com/muan/emojilib/blob/master/emojis.json
https://github.com/milesj/emojibase/blob/master/packages/data/en/data.json (generated from the Unicode standard)

**Comment by b4b4r07** [comment]
It is `emoji.json` which is provided by this repo's dict. But this repo's one is older a bit. So it may be better to use other `emoji.json`.

However, at least `emoji.json` should follow this format to be interrupted by `emoji-cli` command:

At least `emoji.json` needs to be in the following json format in order to be interpreted as `emoji-cli`:

```json
    {
        "emoji": "😄",
        "code": "U+1F604",
        "description": "smiling face with open mouth and smiling eyes",
        "aliases": [
            "smile"
        ],
        "version": 6,
        "tags": [
            "kao",
            "eye",
            "face",
            "mouth",
            "open",
            "person",
            "smile"
        ]
    },
```

If `emoji.json` you list here are not in this format, you need to convert.

**Comment by b4b4r07** [comment]
Close. If you have other question or something please feel free to reopen. Thanks
